services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cinema
      DB_PASSWORD: cinema
      DB_NAME: cinema_db
      DB_SYNC: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: cinema
      RABBITMQ_PASSWORD: cinema
      RABBITMQ_VHOST: /
      OUTBOX_POLL_MS: 1000
      AUTH_ENABLED: "true"
      AUTH_ADMIN_API_KEY: admin-secret
      AUTH_USER_API_KEY: user-secret
      AUTH_ADMIN_USER_ID: admin-1
      AUTH_DEFAULT_USER_ID: user-1
    ports:
      - "3001:3000"

  postgres:
    image: postgres:16
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema_db"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  redis:
    image: redis:7
    container_name: cinema_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 3s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cinema_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cinema
      RABBITMQ_DEFAULT_PASS: cinema
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  pgdata:
