services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cinema
      DB_PASSWORD: cinema
      DB_NAME: cinema_db
      DB_SYNC: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: cinema
      RABBITMQ_PASSWORD: cinema
      RABBITMQ_VHOST: /
      OUTBOX_POLL_MS: 1000
    ports:
      - "3001:3000"

  postgres:
    image: postgres:16
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cinema_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cinema_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cinema
      RABBITMQ_DEFAULT_PASS: cinema

volumes:
  pgdata:
